services:
  lacomart-web:
    build: .
    image: lacomart-web:latest
    container_name: lacomart-web
    ports:
      - "8080:80"
    depends_on:
      - lacomart-db
    restart: always

  lacomart-db:
    image: mysql:8.0
    container_name: lacomart-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: etoko
      MYSQL_USER: zainuri
      MYSQL_PASSWORD: zainuri
    volumes:
      - db_data:/var/lib/mysql
      - ./etoko.sql:/docker-entrypoint-initdb.d/etoko.sql:ro
    ports:
      - "3306:3306"
    restart: always

volumes:
  db_data:
